wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.11.1
    start_time: 1676495715.21323
    t:
      1:
      - 33
      - 55
      2:
      - 33
      - 55
      3:
      - 2
      - 23
      4: 3.11.1
      5: 0.13.10
      8:
      - 1
      - 3
      - 5
